import type { Product, ProductDepartment } from './types'

export const DEPARTMENTS: ProductDepartment[] = ['Food', 'Beverage', 'Retail']

export const GROUPS_BY_DEPARTMENT: Record<ProductDepartment, string[]> = {
  Food: ['Rice', 'Salads', 'Soup', 'Pizza'],
  Beverage: ['Coffee', 'Soft Drinks', 'Juice'],
  Retail: ['Merchandise', 'To-Go'],
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    sku: 'SAL-001',
    name: 'Shrimp Basil Salad',
    priceCents: 1000,
    department: 'Food',
    group: 'Salads',
    emoji: '🥗',
    accent: '#dcfce7',
  },
  {
    id: 'p2',
    sku: 'FD-001',
    name: 'Onion Rings',
    priceCents: 1000,
    department: 'Food',
    group: 'Pizza',
    emoji: '🧅',
    accent: '#ffedd5',
  },
  {
    id: 'p3',
    sku: 'SAL-002',
    name: 'Fresh Basil Salad',
    priceCents: 1000,
    department: 'Food',
    group: 'Salads',
    emoji: '🥬',
    accent: '#ecfccb',
  },
  {
    id: 'p4',
    sku: 'PIZ-001',
    name: 'Cheese Burger',
    priceCents: 1000,
    department: 'Food',
    group: 'Pizza',
    emoji: '🍔',
    accent: '#fef3c7',
  },
  {
    id: 'p5',
    sku: 'PIZ-002',
    name: 'Margherita Pizza',
    priceCents: 1000,
    department: 'Food',
    group: 'Pizza',
    emoji: '🍕',
    accent: '#fee2e2',
  },
  {
    id: 'p6',
    sku: 'BEV-001',
    name: 'Orange Juice',
    priceCents: 1000,
    department: 'Beverage',
    group: 'Juice',
    emoji: '🍊',
    accent: '#ffedd5',
  },
  {
    id: 'p7',
    sku: 'RICE-001',
    name: 'Chicken Rice Bowl',
    priceCents: 1450,
    department: 'Food',
    group: 'Rice',
    emoji: '🍚',
    accent: '#fef9c3',
  },
  {
    id: 'p8',
    sku: 'SOUP-001',
    name: 'Tomato Bisque',
    priceCents: 850,
    department: 'Food',
    group: 'Soup',
    emoji: '🥣',
    accent: '#ffedd5',
  },
  {
    id: 'p9',
    sku: 'BEV-002',
    name: 'Iced Latte',
    priceCents: 1200,
    department: 'Beverage',
    group: 'Coffee',
    emoji: '☕',
    accent: '#e0e7ff',
  },
  {
    id: 'p10',
    sku: 'RICE-002',
    name: 'Nasi Lemak',
    priceCents: 1100,
    department: 'Food',
    group: 'Rice',
    emoji: '🍛',
    accent: '#fce7f3',
  },
  {
    id: 'p11',
    sku: 'SOUP-002',
    name: 'Miso Soup',
    priceCents: 700,
    department: 'Food',
    group: 'Soup',
    emoji: '🍜',
    accent: '#fef3c7',
  },
  {
    id: 'p12',
    sku: 'PIZ-003',
    name: 'Pepperoni Slice',
    priceCents: 950,
    department: 'Food',
    group: 'Pizza',
    emoji: '🍕',
    accent: '#fee2e2',
  },
  {
    id: 'p13',
    sku: 'BEV-003',
    name: 'Cola',
    priceCents: 450,
    department: 'Beverage',
    group: 'Soft Drinks',
    emoji: '🥤',
    accent: '#fee2e2',
  },
  {
    id: 'p14',
    sku: 'BEV-004',
    name: 'Espresso',
    priceCents: 550,
    department: 'Beverage',
    group: 'Coffee',
    emoji: '☕',
    accent: '#ede9fe',
  },
  {
    id: 'p15',
    sku: 'RET-001',
    name: 'Branded Tote Bag',
    priceCents: 1500,
    department: 'Retail',
    group: 'Merchandise',
    emoji: '👜',
    accent: '#e0f2fe',
  },
  {
    id: 'p16',
    sku: 'RET-002',
    name: 'Sauce Bottle',
    priceCents: 800,
    department: 'Retail',
    group: 'To-Go',
    emoji: '🫙',
    accent: '#fef3c7',
  },
]
